"""Create discussion comments table

Revision ID: 14ae49c1cb0d
Revises: 6bd92d9e1b4c
Create Date: 2025-12-24 17:58:19.749879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ae49c1cb0d'
down_revision: Union[str, Sequence[str], None] = '6bd92d9e1b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussion_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('discussion_thread_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['discussion_thread_id'], ['discussion_threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discussion_comments_discussion_thread_id'), 'discussion_comments', ['discussion_thread_id'], unique=False)
    op.create_index(op.f('ix_discussion_comments_user_id'), 'discussion_comments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discussion_comments_user_id'), table_name='discussion_comments')
    op.drop_index(op.f('ix_discussion_comments_discussion_thread_id'), table_name='discussion_comments')
    op.drop_table('discussion_comments')
    # ### end Alembic commands ###
