"""Add image path to discussion threads

Revision ID: d5fd17ab9677
Revises: 14ae49c1cb0d
Create Date: 2025-12-27 19:27:33.728175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5fd17ab9677'
down_revision: Union[str, Sequence[str], None] = '14ae49c1cb0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discussion_threads', sa.Column('image_path', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discussion_threads', 'image_path')
    # ### end Alembic commands ###
